# Generated by Django 5.0.6 on 2024-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('isbn', models.CharField(max_length=17)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
